# These are supported funding model platforms

github: YOUTACRANDS-VA
patreon: patreon.com/user?u=107365027
open_collective: Vincent10
custom: ["https://youtacrs.wordpress.com", "https://youtacrs8.wordpress.com"]
